package manager;

import com.itextpdf.text.*;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.util.ArrayList;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.DB;
import model.Lib;
import static model.Lib.*;
import model.Manager;

/**
 *
 * @author hctha_000
 */
public class GiaVe extends javax.swing.JFrame {

    static DB db = new DB();
    static Manager manager;
    ArrayList<String> typeVehicle ;
    
    public GiaVe(Manager manager) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setVisible(true);
        this.manager = manager;
        setTitle("Cập nhật giá vé - " + manager.name);
        
        //Set Các loại xe mà bãi xe có thể chứa
        this.typeVehicle = this.manager.getTypeVehicle();
        if(typeVehicle != null && typeVehicle.size() > 0) for (String thisType : typeVehicle) {
                jComboBox_LoaiXe.addItem(thisType);
            }
        //Load bảng xe vào từ DB
        this.loadTableFares();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_GiaVe = new javax.swing.JTextField();
        jComboBox_LoaiXe = new javax.swing.JComboBox<>();
        buttonRefresh = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        buttonLogout = new javax.swing.JButton();
        buttonTurnBack = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableGiaVe = new javax.swing.JTable();
        buttonUpdateFares = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        jLabel1.setText("Loại Xe");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 290, 70, 30);

        jLabel2.setText("Giá vé");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(350, 290, 100, 30);
        jPanel1.add(jTextField_GiaVe);
        jTextField_GiaVe.setBounds(460, 290, 120, 30);

        jComboBox_LoaiXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_LoaiXeActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_LoaiXe);
        jComboBox_LoaiXe.setBounds(140, 290, 120, 30);

        buttonRefresh.setText("Refresh");
        buttonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(buttonRefresh);
        buttonRefresh.setBounds(970, 340, 120, 30);

        jButton2.setText("Xuất File");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(820, 340, 120, 30);

        buttonLogout.setText("Đăng xuất");
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(buttonLogout);
        buttonLogout.setBounds(820, 390, 120, 30);

        buttonTurnBack.setText("Back");
        buttonTurnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTurnBackActionPerformed(evt);
            }
        });
        jPanel1.add(buttonTurnBack);
        buttonTurnBack.setBounds(970, 390, 120, 30);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(1140, 290, 200, 30);

        TableGiaVe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Bãi Xe", "Mã Số", "Giá vé", "Loại Xe", "Cập Nhật Lần Cuối"
            }
        ));
        TableGiaVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TableGiaVeMouseReleased(evt);
            }
        });
        TableGiaVe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TableGiaVeKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(TableGiaVe);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(50, 50, 890, 220);

        buttonUpdateFares.setText("Cập nhật");
        buttonUpdateFares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateFaresActionPerformed(evt);
            }
        });
        jPanel1.add(buttonUpdateFares);
        buttonUpdateFares.setBounds(290, 360, 120, 30);

        jLabel3.setText("Bảng quản lí giá vé");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(450, 10, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshActionPerformed
       this.loadTableFares();
    }//GEN-LAST:event_buttonRefreshActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        xuatFile(TableGiaVe,"GiaVe");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        this.dispose();
        LoginForm newlogin = new LoginForm();
        newlogin.showWindows();
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void buttonTurnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTurnBackActionPerformed
        this.dispose();
        ManagerForm newManagerForm = new ManagerForm(manager.id);
        newManagerForm.showWindows();
    }//GEN-LAST:event_buttonTurnBackActionPerformed

    private void TableGiaVeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableGiaVeMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TableGiaVeMouseReleased

    private void TableGiaVeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableGiaVeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TableGiaVeKeyReleased

    private void jComboBox_LoaiXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_LoaiXeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_LoaiXeActionPerformed

    private void buttonUpdateFaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateFaresActionPerformed
        capNhatGiaVe();
    }//GEN-LAST:event_buttonUpdateFaresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiXeVaoRa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiXeVaoRa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiXeVaoRa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiXeVaoRa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaVe(manager).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableGiaVe;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JButton buttonTurnBack;
    private javax.swing.JButton buttonUpdateFares;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox_LoaiXe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField_GiaVe;
    // End of variables declaration//GEN-END:variables



    void showWindows() {
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

//    private void xuatHoaDon() {
//        String[] tenCot = {"Mã Độc Giả","Tên Độc Giả","MSSV","Lớp","Khóa","Giới Tính","Ngày Sinh","SĐT","Địa Chỉ","Ngày Tạo"};;
//        String title = "                                                                          Tìm Kiếm Độc Giả";
//        String fileName = "TimKiemDocGia";
//        String bf = "                             Họ và tên         : Lê Ngọc Long\n"
//                + "                              MSSV              : 20142659\n"
//                + "                              Đề tài               : Xây dựng chương trình quản lý thư viện";
//        bf += "\n\n                              Trường Đại Học Bách Khoa Hà Nội                                                                                                           Cộng Hòa - Xã Hội - Chủ Nghĩa - Việt Nam\n"
//                + "                                    Thư viện Tạ Quang Bửu                                                                                                                                Độc Lập - Tự Do - Hạnh Phúc" ;
//        bf += "\n\n                                                           " +title.toUpperCase();
//        
//        
//        String af = "                              Hà Nội, Việt Nam Ngày "+ Model.ThuVien.getTodayNgayThangNam()+"\n" +
//                     "                              Người tạo bảng : Lê Ngọc Long";
//        
//        
//        Model.ThuVien.xuatFilePDF2(fileName, bf,tenCot,af,TableXeVao, title,PageSize.A2);
//    }
    public void loadTableFares(){
     // Reset lại bảng
     DefaultTableModel dm = (DefaultTableModel) TableGiaVe.getModel();
        int rowCount = dm.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
        
    //Load bảng xe vào từ DB
        ArrayList<ArrayList<String>> faresHistory = this.manager.getFareHistory();
        if(faresHistory != null && faresHistory.size() > 0) {
        for (ArrayList<String> thisFare : faresHistory) {
            String[] rowData = thisFare.toArray(new String[thisFare.size()]);
               dm.addRow(rowData);
            }
        }
    }
    private void capNhatGiaVe() {
        String typeVehicle = (String) jComboBox_LoaiXe.getSelectedItem();
        String giaVe = jTextField_GiaVe.getText();
        if(!checkDouble(giaVe)) JOptionPane.showMessageDialog(null, "Kiểm tra lại giá vé");
        else  {
        if(this.manager.updateFares(typeVehicle,giaVe )) {JOptionPane.showMessageDialog(null, "Cập nhật giá vé thành công");this.loadTableFares();}
        else JOptionPane.showMessageDialog(null, "Cập nhật giá vé thất bại");
        }
    }
//     private void xoaGiaVe() {
//          int[] giaVeSelectedRows = TableGiaVe.getSelectedRows();
//          int giaVeDuocChon = giaVeSelectedRows.length;
//        if (giaVeDuocChon <= 0 ) {
//            JOptionPane.showMessageDialog(null, "Bạn phải chọn ít nhất 1 giá vé");
//        } else {
//                TableModel model = (TableModel) TableGiaVe.getModel();
//                for(int i = 0; i < giaVeDuocChon; i++){
//                    String id = model.getValueAt(giaVeSelectedRows[i], 2).toString();
//                    String fareValue = model.getValueAt(giaVeSelectedRows[i], 3).toString();
//                    String typeVehicle = model.getValueAt(giaVeSelectedRows[i], 4).toString();
//                    String lastUpdate = model.getValueAt(giaVeSelectedRows[i], 5).toString();
//                    String alert = "Bạn có muốn xóa giá vé xe " + typeVehicle + " có giá trị " + fareValue + " được cập nhật lần cuối " + lastUpdate + " không?";
//                    if (JOptionPane.showConfirmDialog(null, alert) == JOptionPane.YES_OPTION) {
//                        if (this.manager.deleteFares(id)) {
//                            JOptionPane.showMessageDialog(null, "Xóa vé xe thành công");
//                        } else {
//                            JOptionPane.showMessageDialog(null, "Xóa vé xe thất bại");
//                        }
//                    }                
//                }
//                
//                loadTableFares();
//                
//            
//            }
//    }
//     
     
private void xuatFile(JTable table, String fileName) {
        String url = fileName;
        String[] tenCot = {"STT","Bãi Xe","Mã số","Giá Vé","Loại Xe","Cập Nhật Lần Cuối"};
        String title = "  Giá Vé";
        
        String bf = "Họ và tên         : Lê Ngọc Long\n"
                + "MSSV              : 20142659\n"
                + "Phần mềm quản lí bãi giữ xe";
        bf += "\n\nTrường Đại Học Bách Khoa Hà Nội                                                                   Cộng Hòa - Xã Hội - Chủ Nghĩa - Việt Nam\n"
                + " Bãi giữ xe "+manager.parking_name +"                                                                            Độc Lập - Tự Do - Hạnh Phúc" ;
        bf += "\n\n                                                                                         " +title.toUpperCase() +"\n";
        
        
        String af = "Hà Nội, Việt Nam Ngày "+ getTodayNgayThangNam()+"\n" +
                     "Người tạo bảng : " + manager.name;
        
        
        //Model.ThuVien.xuatFilePDF(url,table,title,PageSize.A3);
        model.Lib.xuatFilePDF2(url, bf,tenCot,af,table, title,PageSize.A3);
    }

}
