package admin;


import com.itextpdf.text.PageSize;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import manager.LoginForm;
import model.Admin;
import model.DB;
import static model.Lib.checkNumeric;
import static model.Lib.getTodayNgayThangNam;
import static model.Lib.loadTable;

/**
 *
 * @author hctha_000
 */
public class QuanLyForm extends javax.swing.JFrame {

     static DB db = new DB();
    static Admin admin;
    
    public QuanLyForm(Admin admin) {
 initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setVisible(true);
        this.admin = admin;
        setTitle("Quản lí người quản lí - " + admin.name);
        
        //Load bảng quản lí
        loadQuanLiTable();
    }
    void loadQuanLiTable(){
    loadTable(QuanLiTable, this.admin.getQuanLiTable());
    }
    public void showWindows(){
		//this.setSize(600,600);
		this.setDefaultCloseOperation(EXIT_ON_CLOSE);
		this.setResizable(false);
		this.setLocationRelativeTo(null);
		this.setVisible(true);
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        QuanLiTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField_MaQuanLi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_TenQuanLi = new javax.swing.JTextField();
        jTextField_MatKhau = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_TenDangNhap = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_NgaySinh = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Sdt = new javax.swing.JTextField();
        buttonThemDocGia = new javax.swing.JButton();
        buttonChinhSua = new javax.swing.JButton();
        buttonXoa = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        buttonLogout = new javax.swing.JButton();
        buttonTurnBack = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_BaiXe = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        QuanLiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Quản Lí", "Tên Quản Lí", "Tên Đăng Nhập", "Password", "Ngày Sinh", "SĐT", "Bãi Xe"
            }
        ));
        QuanLiTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                QuanLiTableMouseReleased(evt);
            }
        });
        QuanLiTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                QuanLiTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(QuanLiTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 0, 1310, 260);

        jLabel1.setText("Mã Quản Lí");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 290, 70, 30);
        jPanel1.add(jTextField_MaQuanLi);
        jTextField_MaQuanLi.setBounds(140, 290, 120, 30);

        jLabel2.setText("Tên Quản Lí");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 350, 70, 30);
        jPanel1.add(jTextField_TenQuanLi);
        jTextField_TenQuanLi.setBounds(140, 350, 120, 30);
        jPanel1.add(jTextField_MatKhau);
        jTextField_MatKhau.setBounds(490, 290, 120, 30);

        jLabel3.setText("Mật Khẩu");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(410, 290, 70, 30);
        jPanel1.add(jTextField_TenDangNhap);
        jTextField_TenDangNhap.setBounds(140, 410, 120, 30);

        jLabel4.setText("Tên Đăng Nhập");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 410, 90, 30);

        jLabel7.setText("Ngày sinh");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(410, 350, 70, 30);
        jPanel1.add(jTextField_NgaySinh);
        jTextField_NgaySinh.setBounds(490, 350, 120, 30);

        jLabel8.setText("Số điện thoại");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(400, 410, 80, 30);
        jPanel1.add(jTextField_Sdt);
        jTextField_Sdt.setBounds(490, 410, 120, 30);

        buttonThemDocGia.setText("Thêm");
        buttonThemDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThemDocGiaActionPerformed(evt);
            }
        });
        jPanel1.add(buttonThemDocGia);
        buttonThemDocGia.setBounds(670, 290, 120, 30);

        buttonChinhSua.setText("Sửa");
        buttonChinhSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChinhSuaActionPerformed(evt);
            }
        });
        jPanel1.add(buttonChinhSua);
        buttonChinhSua.setBounds(820, 290, 120, 30);

        buttonXoa.setText("Xóa");
        buttonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXoaActionPerformed(evt);
            }
        });
        jPanel1.add(buttonXoa);
        buttonXoa.setBounds(970, 290, 120, 30);

        jButton2.setText("Xuất file PDF");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(670, 350, 120, 30);

        buttonLogout.setText("Đăng xuất");
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(buttonLogout);
        buttonLogout.setBounds(820, 350, 120, 30);

        buttonTurnBack.setText("Back");
        buttonTurnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTurnBackActionPerformed(evt);
            }
        });
        jPanel1.add(buttonTurnBack);
        buttonTurnBack.setBounds(970, 350, 120, 30);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(1140, 290, 200, 30);

        jLabel9.setText("Bãi Xe");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(400, 470, 80, 30);
        jPanel1.add(jTextField_BaiXe);
        jTextField_BaiXe.setBounds(490, 470, 120, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonThemDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThemDocGiaActionPerformed
        addQuanLi();
    }//GEN-LAST:event_buttonThemDocGiaActionPerformed

    private void buttonChinhSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChinhSuaActionPerformed
           updateQuanLi();
    }//GEN-LAST:event_buttonChinhSuaActionPerformed

    private void buttonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXoaActionPerformed
        xoaQuanLi();
    }//GEN-LAST:event_buttonXoaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        writeToPDF(QuanLiTable,"DanhSachCacQuanLi");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
               this.dispose();
        LoginForm newlogin = new LoginForm();
        newlogin.showWindows();
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void buttonTurnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTurnBackActionPerformed
                this.dispose();
        AdminForm newAdminForm = new AdminForm(admin.id);
        newAdminForm.showWindows();
    }//GEN-LAST:event_buttonTurnBackActionPerformed

    private void QuanLiTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuanLiTableKeyReleased
        
    }//GEN-LAST:event_QuanLiTableKeyReleased

    private void QuanLiTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLiTableMouseReleased
        getNoiDungtuQuanLiTable();
    }//GEN-LAST:event_QuanLiTableMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyForm(admin).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable QuanLiTable;
    private javax.swing.JButton buttonChinhSua;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonThemDocGia;
    private javax.swing.JButton buttonTurnBack;
    private javax.swing.JButton buttonXoa;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_BaiXe;
    private javax.swing.JTextField jTextField_MaQuanLi;
    private javax.swing.JTextField jTextField_MatKhau;
    private javax.swing.JTextField jTextField_NgaySinh;
    private javax.swing.JTextField jTextField_Sdt;
    private javax.swing.JTextField jTextField_TenDangNhap;
    private javax.swing.JTextField jTextField_TenQuanLi;
    // End of variables declaration//GEN-END:variables

    private void getNoiDungtuQuanLiTable() {
        int i = QuanLiTable.getSelectedRow();
        TableModel model = (TableModel) QuanLiTable.getModel();
         if(model.getValueAt(i, 1) != null)jTextField_MaQuanLi.setText(String.valueOf(model.getValueAt(i, 1)));
         else jTextField_MaQuanLi.setText("");
         if(model.getValueAt(i, 2) != null)jTextField_TenQuanLi.setText(String.valueOf(model.getValueAt(i, 2)));
         else jTextField_TenQuanLi.setText("");
         if(model.getValueAt(i, 3) != null)jTextField_TenDangNhap.setText(String.valueOf(model.getValueAt(i, 3)));
         else jTextField_TenDangNhap.setText("");
         if(model.getValueAt(i, 4) != null)jTextField_MatKhau.setText(String.valueOf(model.getValueAt(i, 4)));
         else jTextField_MatKhau.setText("");
         if(model.getValueAt(i, 5) != null)jTextField_NgaySinh.setText(String.valueOf(model.getValueAt(i, 5)));
         else jTextField_NgaySinh.setText("");
         if(model.getValueAt(i, 6) != null)jTextField_Sdt.setText(String.valueOf(model.getValueAt(i, 6)));
         else jTextField_Sdt.setText("");
         if(model.getValueAt(i, 7) != null)jTextField_BaiXe.setText(String.valueOf(model.getValueAt(i, 7)));
         else jTextField_BaiXe.setText("");
    }

    private void addQuanLi() {
         try {
             if(db.insertIngorNull("account", new String[]{"user","pass","name","type","birthday","sdt","parking_id"},
                     new String[]{
                         jTextField_TenDangNhap.getText(),
                         jTextField_MatKhau.getText(),
                         jTextField_TenQuanLi.getText(),
                         "manager",
                         jTextField_NgaySinh.getText(),
                         jTextField_Sdt.getText(),
                     jTextField_BaiXe.getText()})){
                 loadQuanLiTable();
                 JOptionPane.showMessageDialog(null, "Đã thêm thành công quản lí " + jTextField_TenQuanLi.getText());
             } else {
                 JOptionPane.showMessageDialog(null, "Không thể thêm quản lí " +jTextField_TenQuanLi.getText()+" được");
             }} catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, "Không thể thêm quản lí " +jTextField_TenQuanLi.getText()+" được");
         }
    }
    private void updateQuanLi() {
        if(db.updateIngorNull("account", new String[]{"user","pass","name","type","birthday","sdt","parking_id"},
                new String[]{
                    jTextField_TenDangNhap.getText(),
                    jTextField_MatKhau.getText(),
                    jTextField_TenQuanLi.getText(),
                    "manager",
                    jTextField_NgaySinh.getText(),
                    jTextField_Sdt.getText(),
                    jTextField_BaiXe.getText()},
                     "id = " + jTextField_MaQuanLi.getText())){
            loadQuanLiTable();
            JOptionPane.showMessageDialog(null, "Đã cập nhật  thành công quản lí " + jTextField_TenQuanLi.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Không thể cập nhật quản lí " +jTextField_TenQuanLi.getText()+" được");
        }
    }

    private void xoaQuanLi() {
        int[] xeSelectedRows = QuanLiTable.getSelectedRows();
          int soXeDuocChon = xeSelectedRows.length;
        if (soXeDuocChon <= 0 ) {
            JOptionPane.showMessageDialog(null, "Bạn phải chọn ít nhất 1 quản lí");
        } else {
                TableModel model = (TableModel) QuanLiTable.getModel();
                for(int i = 0; i < soXeDuocChon; i++){
                    String id = model.getValueAt(xeSelectedRows[i], 1).toString();
                    String name = model.getValueAt(xeSelectedRows[i], 2).toString();
                    String alert = "Bạn có muốn xóa quản lí " + name  + " không?";
                    if (JOptionPane.showConfirmDialog(null, alert) == JOptionPane.YES_OPTION) {
                        if (this.admin.deleteQuanLi(id)) {
                            JOptionPane.showMessageDialog(null, "Xóa quản lí " +name+ " thành công");
                        } else {
                            JOptionPane.showMessageDialog(null, "Xóa quản lí " +name+ " thất bại");
                        }
                    }                
                }
                
                loadQuanLiTable();
                
            
            }
    }

    private void writeToPDF(JTable table, String fileName) {
        String url = fileName;
        String[] tenCot = {"STT","Mã Quản Lí","Tên Quản Lí","Tên Đăng Nhập","Mật Khẩu","Ngày Sinh","Số Điện Thoại","Bãi Xe"};
        String title = "Danh Sách Các Quản Lí";
        String loaiThongKe = "";
        
        String bf = "Họ và tên         : Lê Ngọc Long\n"
                + "MSSV              : 20142659\n"
                + "Phần mềm quản lí bãi giữ xe";
        bf += "\n\nTrường Đại Học Bách Khoa Hà Nội                                                                   Cộng Hòa - Xã Hội - Chủ Nghĩa - Việt Nam\n"
                + "                                                                                                                                      Độc Lập - Tự Do - Hạnh Phúc" ;
        bf += "\n\n                                                                              " +title.toUpperCase() +"\n";
        bf+= loaiThongKe.toUpperCase();
        
        
        String af = "Hà Nội, Việt Nam Ngày "+ getTodayNgayThangNam()+"\n" +
                     "Người tạo bảng : " + admin.name;
        
        
        //Model.ThuVien.xuatFilePDF(url,table,title,PageSize.A3);
        model.Lib.xuatFilePDF2(url, bf,tenCot,af,table, title,PageSize.A3);
    }



    
}
