package admin;

import com.itextpdf.text.PageSize;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Set;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.DB;
import static model.Lib.*;
import model.Admin;
import org.apache.poi.xssf.usermodel.*;
import static admin.QuanLiXeVaoRa.admin;

/**
 *
 * @author Long
 */
public class ThongKeForm extends javax.swing.JFrame {

    static DB db = new DB();
    static Admin admin;
    ArrayList<String> typeVehicle ;
    
    public ThongKeForm(Admin admin) {
        
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setVisible(true);
        this.admin = admin;
        setTitle("Thống kê - " + admin.name);
        
        //Load bảng xe vào từ DB
        this.loadDanhSachBaiXe();
        
        
    }
    public void loadDanhSachBaiXe(){
    //Load bảng xe vào từ DB
        if(db.selectQuick("id", "parking_info", "1")){
        ArrayList<ArrayList<String>> arr = db.kq;
            for (ArrayList<String> arrayList : arr) {
                jComboBox1.addItem(arrayList.get(0));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ComboBox_LoaiXe = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ComboBox_TrangThai = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Label_TongTien = new javax.swing.JLabel();
        Label_LuotGui = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ThongKeTable = new javax.swing.JTable();
        dateChooserComboTo = new datechooser.beans.DateChooserCombo();
        dateChooserComboFrom = new datechooser.beans.DateChooserCombo();
        jLabel5 = new javax.swing.JLabel();
        ComboBox_ThoiGianVaoRa = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox_LoaiThongKe = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Từ ngày");
        jLabel1.setMaximumSize(new java.awt.Dimension(34, 14));
        jLabel1.setMinimumSize(new java.awt.Dimension(34, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(34, 14));

        jLabel2.setText("Đến ngày");

        jLabel3.setText("Loại xe");

        ComboBox_LoaiXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất Cả", "Xe Máy", "Oto", "Xe Đạp", "Xe Đạp Điện" }));
        ComboBox_LoaiXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_LoaiXeActionPerformed(evt);
            }
        });

        jLabel4.setText("Trạng thái");

        ComboBox_TrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất Cả", "Đang trong bãi", "Đã ra" }));

        jButton1.setText("Thống kê");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Xuất file PDF");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Label_TongTien.setText("Tổng số tiền: 200000 VND");

        Label_LuotGui.setText("120 lượt");

        ThongKeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Xe Vào Ra", "Biển Kiểm Soát", "Thời Gian Vào", "Thời Gian Ra", "Loại Xe", "Trạng Thái", "Thành Tiền"
            }
        ));
        jScrollPane1.setViewportView(ThongKeTable);

        dateChooserComboTo.setCalendarPreferredSize(new java.awt.Dimension(500, 360));

        dateChooserComboFrom.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateChooserComboFrom.setCalendarPreferredSize(new java.awt.Dimension(500, 360));

    jLabel5.setText("Theo");

    ComboBox_ThoiGianVaoRa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thời Gian Vào", "Thời Gian Ra" }));

    jButton3.setText("Xuất file Excel");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });

    jButton4.setText("Back");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
        }
    });

    jLabel6.setText("Danh sách các bãi xe");

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả" }));
    jComboBox1.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            jComboBox1ItemStateChanged(evt);
        }
    });
    jComboBox1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox1ActionPerformed(evt);
        }
    });

    jLabel7.setText("Thống kê theo");

    jComboBox_LoaiThongKe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày", "Tuần", "Tháng", "Năm" }));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(515, 515, 515)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(33, 33, 33)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(37, 37, 37)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(84, 84, 84)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGap(26, 26, 26)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ComboBox_LoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateChooserComboFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(121, 121, 121)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4))
                    .addGap(37, 37, 37)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dateChooserComboTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ComboBox_TrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(80, 80, 80)
                    .addComponent(jLabel5)
                    .addGap(50, 50, 50)
                    .addComponent(ComboBox_ThoiGianVaoRa, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(418, 418, 418)
                    .addComponent(Label_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(Label_LuotGui, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(22, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(66, 66, 66)
            .addComponent(jComboBox_LoaiThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(458, 458, 458))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(53, 53, 53)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addComponent(dateChooserComboFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateChooserComboTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBox_TrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(ComboBox_ThoiGianVaoRa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ComboBox_LoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGap(21, 21, 21)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox_LoaiThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(36, 36, 36)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton3)
                        .addComponent(jButton4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Label_LuotGui, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Label_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jLabel6)
                    .addGap(16, 16, 16)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(51, 51, 51)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(131, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(302, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.thongKe();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        writeToPDF(ThongKeTable,"ThongKeVaoRa");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        writeToExcel(ThongKeTable,"ThongKeVaoRa");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        AdminForm newAdminForm = new AdminForm(admin.id);
        newAdminForm.showWindows();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        String baixe = (String)jComboBox1.getSelectedItem();
        if(baixe.equalsIgnoreCase("Tất cả")) this.admin.parking_id = "all";
        else this.admin.parking_id = baixe;
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void ComboBox_LoaiXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_LoaiXeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_LoaiXeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeForm(admin).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_LoaiXe;
    private javax.swing.JComboBox<String> ComboBox_ThoiGianVaoRa;
    private javax.swing.JComboBox<String> ComboBox_TrangThai;
    private javax.swing.JLabel Label_LuotGui;
    private javax.swing.JLabel Label_TongTien;
    private javax.swing.JTable ThongKeTable;
    private datechooser.beans.DateChooserCombo dateChooserComboFrom;
    private datechooser.beans.DateChooserCombo dateChooserComboTo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox_LoaiThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables






void showWindows() {
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }


void thongKe(){
        try {
            String timeIn = dateChooserComboFrom.getText();
            String timeOut = dateChooserComboTo.getText();
            DateFormat df = new SimpleDateFormat("MM/dd/yy");
            if(timeIn != null && timeIn.length() > 0 && timeIn.contains("/")){
            Date from = df.parse(timeIn);
            timeIn = new SimpleDateFormat("yyyy/MM/dd").format(from);
            } else timeIn = null;
            if(timeOut != null && timeOut.length() > 0 && timeOut.contains("/")){
            Date to = df.parse(timeOut);
            timeOut = new SimpleDateFormat("yyyy/MM/dd").format(to);
            } else timeOut = null;
            
            String trangThai = ComboBox_TrangThai.getSelectedItem().toString();
            String loaiXe = ComboBox_LoaiXe.getSelectedItem().toString();
            String loaiThongKe = jComboBox_LoaiThongKe.getSelectedItem().toString();
            String ThoiGianVaoRa = ComboBox_ThoiGianVaoRa.getSelectedItem().toString();
            
            int tongTien = 0;
// Reset lại bảng
     DefaultTableModel dm = (DefaultTableModel) ThongKeTable.getModel();
        int rowCount = dm.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
        
    //Load bảng thống kê vào từ DB
        ArrayList<ArrayList<String>> thongKe = this.admin.getThongKe(timeIn, timeOut,loaiXe, trangThai,ThoiGianVaoRa, loaiThongKe);
        if(thongKe != null && thongKe.size() > 0) {
            for (int i = 0; i < thongKe.size(); i++) {
                ArrayList<String> thisThongKe = thongKe.get(i);
                thisThongKe.add(0, String.valueOf(i + 1));
                if(checkNumeric(thisThongKe.get(2))) tongTien += Integer.valueOf(thisThongKe.get(2));
                String[] rowData = thisThongKe.toArray(new String[thisThongKe.size()]);
               dm.addRow(rowData);
            }    
           
        //Tính tổng số tiền
        Label_TongTien.setText("Tổng số tiền: " +String.valueOf(tongTien) + " VNĐ");
        //Luot giu xe
        Label_LuotGui.setText(String.valueOf(thongKe.size()) + " lượt gửi");
} else {
        Label_TongTien.setText("");
        Label_LuotGui.setText("");
        }
        
        
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Đã có lỗi xảy ra");
        }
}
private void writeToPDF(JTable table, String fileName) {
        String url = fileName;
        String[] tenCot = {"STT","Lượt Gửi","Doanh Thu",(String)jComboBox_LoaiThongKe.getSelectedItem()};
        String title = "  Thống Kê Vào Ra";
        String loaiThongKe = "";
        
            String timeIn = dateChooserComboFrom.getText();
            String timeOut = dateChooserComboTo.getText();
            DateFormat df = new SimpleDateFormat("MM/dd/yy");
            try{
            if(timeIn != null && timeIn.length() > 0 && timeIn.contains("/")){
            Date from = df.parse(timeIn);
            timeIn = new SimpleDateFormat("dd/MM/yyyy").format(from);
            loaiThongKe += " từ ngày " + timeIn;
            } else timeIn = null;
            if(timeOut != null && timeOut.length() > 0 && timeOut.contains("/")){
            Date to = df.parse(timeOut);
            timeOut = new SimpleDateFormat("dd/MM/yyyy").format(to);
            loaiThongKe += " tới ngày " + timeOut;
            } else timeOut = null;
            } catch (Exception ex){
                System.err.println(ex);
            }
            
            String moreInfo = "";
            if(Label_TongTien.getText() != null && Label_TongTien.getText().length() > 1) moreInfo += "\n" + Label_TongTien.getText() ;
            if(Label_LuotGui.getText() != null && Label_LuotGui.getText().length() > 1) moreInfo += " ( " + Label_LuotGui.getText() + " )";
        
        String bf = "Họ và tên         : Lê Ngọc Long\n"
                + "MSSV              : 20142659\n"
                + "Phần mềm quản lí bãi giữ xe";
        bf += "\n\nTrường Đại Học Bách Khoa Hà Nội                                                                   Cộng Hòa - Xã Hội - Chủ Nghĩa - Việt Nam\n"
                + " Bãi giữ xe "+admin.parking_name +"                                                                            Độc Lập - Tự Do - Hạnh Phúc" ;
        bf += "\n\n                                                                                         " +title.toUpperCase() +"\n";
        bf+= loaiThongKe.toUpperCase();
        bf+= moreInfo;
        
        
        String af = "Hà Nội, Việt Nam Ngày "+ getTodayNgayThangNam()+"\n" +
                     "Người tạo bảng : " + admin.name;
        
        
        //Model.ThuVien.xuatFilePDF(url,table,title,PageSize.A3);
        model.Lib.xuatFilePDF2(url, bf,tenCot,af,table, title,PageSize.A3);
    }

public void writeToExcel(JTable table, String fileName){
//    try{
   DefaultTableModel dm = (DefaultTableModel) table.getModel();
   XSSFWorkbook wb = new XSSFWorkbook();
   XSSFSheet ws = wb.createSheet();
   
   //Load data to Treemap
   TreeMap<String,Object[]> data = new TreeMap();
   data.put("0", new Object[]{dm.getColumnName(0),dm.getColumnName(1),dm.getColumnName(2),dm.getColumnName(3)});
        for (int i = 0; i < dm.getRowCount(); i++) {
            data.put(String.valueOf(i+1), new Object[]{
                getCellVal(dm,i,0),
                getCellVal(dm,i,1),
                getCellVal(dm,i,2),
                getCellVal(dm,i,3),
                });
        }
   //Write to sheet
   Set<String> ids = data.keySet();
   XSSFRow row ;
   int rowID = 0;
   
   for(String key:ids){
   row = ws.createRow(rowID++);
   //get data as per key
   Object[] values = data.get(key);
   int cellID = 0;
   for(Object o : values){
   XSSFCell cell = row.createCell(cellID++);
   if(o != null) cell.setCellValue(String.valueOf(o));
   else cell.setCellValue("");
   }
   }
   
   //Write excell to file system
   xuatFileExcel(fileName,wb);
   
//} catch(Exception ex){
//            System.err.println(ex);
//}
}
}
